name: Prose linting

on:
  - push
  - pull_request

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: vale
        uses: errata-ai/vale-action@reviewdog
        with:
          # Cause the check to fail on any broke rules
          fail_on_error: true

